[logger]
level = "debug"
file = "sender_log.txt"

[rabbit]
conn_string="amqp://guest:guest@calendar_rabbitmq:5672"
exchange="events_exchange"
queue="notification_queue"

[dbstorage]
conn_string="postgres://pguser:pgpwd@calendar_postgres:5432/calendar?sslmode=disable"